### ISSUE TITLE
npm ERR! code E409

### ISSUE THREAD

**Issue by michidk** [aslafy-z/conventional-pr-title-action#308] opened 2023-12-16 10:21 UTC
Title `fix(deps): update rust crate clap-verbosity-flag to 2.1.1` adheres to the conventional commits standards, but action output says otherwisse.

Affected PR: https://github.com/michidk/vscli/pull/51

```
Run aslafy-z/conventional-pr-title-action@v3
  with:
    success-state: Title follows the specification.
    failure-state: Title does not follow the specification.
    context-name: conventional-pr-title
    preset: conventional-changelog-conventionalcommits@5.0.0
    target-url: https://www.conventionalcommits.org/en/v1.0.0/#summary
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name bfbe3f17ed031b913a48e9bbc644358bd2036c_90dc46 --label bfbe3f --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "INPUT_SUCCESS-STATE" -e "INPUT_FAILURE-STATE" -e "INPUT_CONTEXT-NAME" -e "INPUT_PRESET" -e "INPUT_TARGET-URL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/vscli/vscli":"/github/workspace" bfbe3f:17ed031b913a48e9bbc644358bd2036c
Error: Command failed: npm install --quiet conventional-changelog-conventionalcommits@5.0.0
npm ERR! code E409
npm ERR! 409 Conflict - GET https://registry.npmjs.org/q/-/q-1.5.1.tgz

npm ERR! A complete log of this run can be found in: /github/home/.npm/_logs/2023-12-15T21_49_50_970Z-debug-0.log
```

Full logs:
[logs_522.zip](https://github.com/aslafy-z/conventional-pr-title-action/files/13692222/logs_522.zip)

**Comment by aslafy-z** [comment] 2024-01-13 14:16
Thank you for reporting this issue. This plugin operates by installing the necessary packages at runtime, which means it's subject to temporary internet issues or conflicts arising from the npm registry. Since there is no `package-lock.json` file attached (the configuration only references the package to install, in this case, `conventional-changelog-conventionalcommits@5.0.0`), the action is also sensitive to any changes in the versions of these packages. This could be the reason for the error you encountered.

I've attempted to reproduce the issue but haven't encountered the same problem, and it appears that the action is now functioning correctly on the pull requests in your repository. This suggests that the issue might have been a temporary one, possibly related to npm registry conflicts at the time of execution.

Given these observations and the fact that the issue seems to be resolved now, I am closing this issue. However, if you continue to experience problems or have any further concerns, please feel free to reopen it or create a new issue.

**Closed by aslafy-z** 2024-01-13 14:16 UTC
